[package]
authors = ["Shinyzenith <https://aakash.is-a.dev>"]
description = "Screenshot crate for wlroots based compositors implementing the zwlr_screencopy_v1 protocol."
keywords = ["screenshot", "wayland", "wlroots", "wayshot"]
license = "BSD-2-Clause"
repository = "https://git.sr.ht/~shinyzenith/wayshot"
name = "libwayshot"
version = "0.2.0"
edition = "2021"

[dependencies]
image = { version = "0.24", default-features = false }
memmap2 = "0.9.0"
nix = { version = "0.27.1", features = ["fs", "mman"] }
thiserror = "1"
tracing = "0.1.40"
wayland-client = "0.31.1"
wayland-protocols = { version = "0.31.0", features = ["client", "unstable"] }
wayland-protocols-wlr = { version = "0.2.0", features = ["client"] }
