[package]
name = "libwayshot"
version = "0.3.2-dev"
authors.workspace = true
description.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
tracing.workspace = true
image = { version = "0.25", default-features = false }
memmap2 = "0.9.0"
rustix = { version = "0.38", features = ["fs", "shm"] }
thiserror = "1"

wayland-client = "0.31.1"
wayland-protocols = { version = "0.31.0", features = ["client", "unstable"] }
wayland-protocols-wlr = { version = "0.2.0", features = ["client"] }
