[package]
name = "waymirror-egl"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
gl = "0.14.0"
gl_loader = "0.1.2"
thiserror = "2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
r-egl-wayland.workspace = true
wayland-client = { version = "0.31.8" }
wayland-egl = { version = "0.32.5" }
wayland-protocols = { version = "0.32.6", features = ["client"] }
libwayshot.workspace = true
libloading = "0.9.0"

