name: Build Wayshot

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy rustfmt
    - name: Install wayland dependencies
      run: |
        pacman -Syu --noconfirm egl-wayland egl-gbm wayland base-devel mesa pango cairo libjxl

    - name: Build
      run: |
        rm Cargo.lock
        cargo build --workspace --release
    - name: Clippy check
      run:
        cargo clippy -- -D warnings
    - name: Check test
      run: |
        cargo test --verbose

  coverage:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview

    - name: Install wayland dependencies
      run: |
        pacman -Syu --noconfirm git egl-wayland egl-gbm wayland base-devel mesa pango cairo libjxl

    - name: Install cargo-llvm-cov
      run: |
        cargo install cargo-llvm-cov

    - name: Generate coverage report
      run: |
        cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./lcov.info
        fail_ci_if_error: false
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  rustfmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Check formatting
      run: |
        cargo fmt -- --check

  documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Check docs
      run: |
        sudo apt update
        sudo apt install --no-install-recommends scdoc
        for file in $(find . -type f -iwholename "./docs/*.scd"); do scdoc < $file > /dev/null; done

  publish-crate:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    permissions:
      contents: write
      id-token: write
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - build
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy rustfmt
    - name: Install wayland dependencies
      run: |
        pacman -Syu --noconfirm egl-wayland egl-gbm wayland base-devel mesa pango cairo libjxl github-cli
    - name: Obtain crates.io token
      uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec # v1.0.3
      id: auth
    - name: Publish to crates.io
      run: |
        cargo publish -p libwayshot
        cargo publish -p wayshot
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        CARGO_PUBLISH: true
    - name: Publish github release
      run: |
        if [[ $(echo "${GTIHUB_REF#refs/tags/v}" | grep '-' > /dev/null) ]]; then
          gh release edit "${GITHUB_REF#refs/tags/}" --prerelease
        fi
        gh release edit "${GITHUB_REF#refs/tags/}" --draft=false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
